version: '2'

services:
  sqlite:
    command: socat TCP-L:12345,fork,reuseaddr EXEC:'sqlite3',pty
    build:
      context: ../webCryptoServeur/
      dockerfile: ../webCryptoDocker/DockerfileSQLite
    container_name: SQLiteTriplet
    ports:
    - 2:12345
    volumes:
    - /home/docker/account:/usr/local/monCoffre/account


  certificat:
    build:
      context: ../webCryptoCertificat
      dockerfile: ../webCryptoDocker/DockerfileCertificat
    container_name: Certificat
    volumes:
      - certifok:/usr/local/certif/

  serveur:
    build:
      context: ../webCryptoServeur/
      dockerfile: ../webCryptoDocker/DockerfileServeur
    container_name: Serveur
    # ports:
    # - "8080:8080"
    volumes:
      # - /home/docker/keycloak/:/opt/
      - keycloakDependency:/usr/local/jetty/lib/keycloak/
    volumes_from:
    - sqlite:rw
    stdin_open: True
    tty: True
    depends_on:
    - sqlite
    # - certificat
    links:
    - "sqlite:sqlite"
    - "authentification:serv"

  reverse_proxy:
    build:
      context: ../webCryptoNGINX/
      dockerfile: ../webCryptoDocker/DockerfileNGINX
    container_name: RevProxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certifok:/etc/nginx/certif/
      # - /home/docker/config/:/etc/nginx/conf.d/
    stdin_open: True
    tty: True
    depends_on:
      - serveur
#      - certificat
    links:
      - "serveur:app"
      - "authentification:authent"


  authentification:
    image: jboss/keycloak
    container_name: Keycloak
#    command:
    depends_on:
      - postgres_auth
    #
    # A enlever pour le https
    #
    ports:
      - "8081:8080"
    networks:
      - keycloak-network



  postgres_auth:
    image: postgres:11.3
    container_name: Postgres_auth
    ports:
      - "5432:5432"
    volumes:
      - volumeAuthentifie:/var/lib/postgresql/data
    networks:
      - keycloak-network



  keycloak_dependency:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
      dockerfile: DockerfileKeycloakDependency
    container_name: Keycloak_dependency
#    env_file:
#      - proxy.env
    volumes:
      - keycloakDependency:/keycloak/lib/keycloak/

volumes:
  certifok:
  volumeAuthentifie:
  keycloakDependency:

networks:
  keycloak-network:
    driver: bridge
