version: '2'

services:
  sqlite:
    command: socat TCP-L:12345,fork,reuseaddr EXEC:'sqlite',pty
    build:
      context: ../webCryptoServeur/
      dockerfile: ../webCryptoDocker/DockerfileSQLite
    container_name: SQLiteTriplet
    ports:
    - 2:12345
    volumes:
    - /home/docker/:/usr/local/monCoffre

  serveur:
    build:
      context: ../webCryptoServeur/
      dockerfile: ../webCryptoDocker/DockerfileServeur
    container_name: Serveur
    ports:
    - "8080:8080"
    volumes_from:
    - sqlite:rw
    stdin_open: True
    tty: True
    depends_on:
    - sqlite
    links:
    - "sqlite:sqlite"
